version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: University
      MYSQL_USER: user
      MYSQL_PASSWORD: Password!2024
    ports:
      - "3306:3306"
    volumes:
      - ../../schema/${PROFILE:-simple}/university-mysql.sql:/docker-entrypoint-initdb.d/init.sql
      - ../../schema/${PROFILE:-simple}/populate-university-db.sql:/docker-entrypoint-initdb.d/insert-scripts.sql
