version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: University
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Password!2024
    ports:
      - "5432:5432"
    volumes:
      - ../../schema/${PROFILE:-simple}/university-postgresql.sql:/docker-entrypoint-initdb.d/init.sql
      - ../../schema/${PROFILE:-simple}/populate-university-db.sql:/docker-entrypoint-initdb.d/insert-scripts.sql